-- Run this once in Supabase → SQL Editor

CREATE TABLE saved_terms (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term        TEXT NOT NULL,
  definition  TEXT,
  practical   TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Allow full access (internal tool, no auth needed)
ALTER TABLE saved_terms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all" ON saved_terms FOR ALL USING (true) WITH CHECK (true);
